#!/bin/bash
# Bspwm settings
apt update && apt upgrade
mkdir -p /home/alan/.config/{bspwm,sxhkd}
cp /home/alan/Downloads/debian/bspwm/autostart.sh /home/alan/.config/bspwm
cp /home/alan/Downloads/debian/bspwm/bspwmrc /home/alan/.config/bspwm
cp /home/alan/Downloads/debian/bspwm/sxhkdrc /home/alan/.config/sxhkd
