#!/bin/bash
rm /etc/apt/sources.list
cp /home/alan/Downloads/debian/sources.list /etc/apt/
apt update && apt upgrade 
rm /etc/profile
cp /home/alan/Downloads/debian/profile /etc
source /etc/profile
cd /home/alan/debian/
dpkg -i google-chrome-stable_current_amd64.deb
apt -f install -s
